Repository dwyl/app, pull requests merged in 2023-03, with the labels that each got.

#321 [PR] Adding splash screen
  web/index.html
Labels: enhancement, awaiting-review, flutter

#323 [PR] Deploy to Github pages.
  .github/workflows/deploy.yml
Labels: awaiting-review, flutter

#324 PR: Remove `--base-href /app/` for #322 when using subdomain app.dwyl.com
  .github/workflows/deploy.yml
Labels: help wanted

#327 PR: Optimise `JS` issue #325
  .github/workflows/deploy.yml
  .gitignore
  web/index.html
Labels: chore, priority-2, technical, spike, awaiting-review, flutter, T5m, research, tech-debt

#330 [PR] Flutter web speed up patch
  .github/workflows/ci.yml
  build_tools/patch_web.sh
  build_tools/web/flutter.js.patch
  build_tools/web/flutter_service_worker.js.patch
  web/index.html
Labels: enhancement, awaiting-review, flutter, documentation
